process.env.TXNAPISTACK_URI=''
process.env.TEST_JWT=''
process.env.TEST_WALLET_ADDRESS=''
process.env.TEST_JWT2=''
process.env.TEST_WALLET_ADDRESS2=''
process.env.PINATA_API_KEY=""
process.env.PINATA_API_SECRET=""
process.env.PINATA_API_URI="https://api.pinata.cloud"
process.env.TEST_TXN=''
process.env.TEST_WALLET_ADDRESS3=''
process.env.TEST_JWT3=''
process.env.TEST_WALLET_ADDRESS4=''
process.env.TEST_JWT4=''
process.env.ALGOD_URI="https://testnet-api.algonode.cloud"
process.env.ALGO_INDEXER_URI="https://testnet-idx.algonode.cloud"
process.env.ALGO_API_TOKEN=""
process.env.ALGOD_INDEXER_PORT=""
process.env.REGION="us-east-1"
//process.env.GRAPHQL_API_KEY="da2-asv2h5mob5cltffibpe3gdxmp4"
//process.env.GRAPHQL_URI="https://nd35u77ygzeh3gssyizbcs3yha.appsync-api.us-east-1.amazonaws.com/graphql"
process.env.MIXPANEL_TOKEN=""
process.env.USE_CREATOR_WHITELIST = "false"
process.env.ADMIN_ID=""
process.env.REWARD_MODULE_ID=""
process.env.SUBSCRIPTION_MODULE_ID=""
process.env.NIFTGEN_ASSET_ID=""
process.env.NIFTGEN_ADDRESS=""

